swagger: '2.0'
info:
  title: Netflix API
  description: Netflix API description.
  version: 1.0.0
host: localhost:10030
produces:
  - application/json
securityDefinitions:
  SessionID:
    type: apiKey
    in: query
    name: SessionID
    description: apikey for X-Session-ID
  AdminApiKey:
    type: apiKey
    in: header
    name: AdminApiKey
    description: apikey for X-Admin-API-key
basePath: /
tags:
  - name: user
    description: Operations about user
  - name: video
    description: Video operations
  - name: admin
    description: Admin operations
schemes:
  - http
paths:
  /user:
    x-swagger-router-controller: user
    post:
      tags:
        - user
      operationId: registerUser
      summary: Create user
      parameters:
        - in: body
          name: body
          description: register new user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Account created
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: failed
  /user/login:
    x-swagger-router-controller: user
    post:
      tags:
        - user
      operationId: login
      summary: Login
      parameters:
        - in: body
          name: body
          description: register new user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: successful login
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid username/password supplied
      
  /user/logout:
    x-swagger-router-controller: user
    get:
      tags:
        - user
      operationId: logout
      summary: Logout
      parameters: []
      responses:
        '200':
          description: successful login
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - SessionID: []
  /video:
    x-swagger-router-controller: video
    get:
      tags:
        - video
      operationId: getVideoByTitle
      summary: Find video by title
      parameters:
        - name: title
          in: query
          type: string
      responses:
        '200':
          description: successful call for video
          schema:
            $ref: '#/definitions/Videos'
        '400':
          description: Video not found
          schema:
            $ref: '#/definitions/ApiResponse'
  /addVideo:
    x-swagger-router-controller: video
    post:
      tags:
        - video
      operationId: addVideoToQueue
      summary: Add video to queue
      parameters:
        - name: title
          in: query
          type: string
      responses:
        '200':
          description: successful added to queue
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - SessionID: []
  /videos:
    x-swagger-router-controller: video
    get:
      operationId: viewQueue
      tags:
        - video
      summary: list user queue
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Videos'
      security:
        - SessionID: []
  /admin/video:
    x-swagger-router-controller: admin
    post:
      tags:
        - admin
      operationId: addVideo
      summary: Add video
      parameters:
        - name: title
          in: query
          type: string
          required: true
        - name: type
          in: query
          type: string
          required: true
        - name: category
          in: query
          type: string
          required: true
      responses:
        '200':
          description: Add video to database
          schema:
            $ref: '#/definitions/Video'
      security:
        - AdminApiKey: []
  /admin/{videoId}:
    x-swagger-router-controller: admin
    get:
      tags:
        - admin
      operationId: getVideo
      summary: Get a video
      parameters:
        - name: videoId
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Get a video from database
          schema:
            $ref: '#/definitions/Video'
        '400':
          description: Video not found
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - AdminApiKey: []
    patch:
      tags:
        - admin
      operationId: updateVideo
      summary: Update video
      parameters:
        - name: videoId
          in: path
          type: string
          required: true
        - name: title
          in: query
          type: string
        - name: type
          in: query
          type: string
        - name: category
          in: query
          type: string
      responses:
        '200':
          description: Add video to database
          schema:
            $ref: '#/definitions/Video'
      security:
        - AdminApiKey: []
    delete:
      tags:
         - admin
      operationId: deleteVideo
      summary: Delete video
      parameters:
      - name: videoId
        in: path
        type: string
        required: true
        description: 'id of the video'
      responses:
        '200':
          description: Video deleted
          schema:
            $ref: '#/definitions/ApiResponse'
      security:
        - AdminApiKey: []
  /admin/allVideo:
    x-swagger-router-controller: admin
    get:
      operationId: allVideo
      tags: 
        - admin
      summary: "Get all the avaiable videos"
      parameters: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Videos'
      security:
        - AdminApiKey: []
definitions:
  User:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
  Users:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        password:
          type: string
  Video:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      type:
        type: string
      category:
        type: string
  Videos:
    type: array
    items:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        tipe:
          type: string
        category:
          type: string        
  ApiResponse:
    required:
      - message
    properties:
      message:
        type: string